name: Linting, Testing, Building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        if: always()

      - name: Run Stylelint
        run: npm run stylelint
        if: always()

      - name: Run unit tests
        run: npm run test
        if: always()

      - name: Build storybook
        run: npm run storybook:build
        if: always()

      - name: Run loki
        run: npm run loki:ci
        if: always()

      - name: Build production project
        run: npm run build:prod
        if: always()
